service: daily-questions-service

frameworkVersion: '>=1.1.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  stage: v1
  region: us-east-1

functions:
  verify-token:
    handler: handlers/verifyToken.token

  login:
    handler: handlers/auth.login
    events:
      - http:
          path: login
          method: post
          cors: true

  register:
    handler: handlers/auth.register
    events:
      - http:
          path: register
          method: post
          cors: true

  me:
    handler: handlers/auth.me
    events:
      - http:
          path: user
          method: get
          cors: true
          authorizer: verify-token

  getQuestionsByUserId:
    handler: handlers/user.getQuestionsByUserId
    events:
      - http:
          path: user/questions
          method: get
          cors: true
          authorizer: verify-token

  getUsers:
    handler: handlers/user.getUsers
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: verify-token

  configFeatures:
    handler: handlers/config.features
    events:
      - http:
          path: config/features
          method: get
          cors: true
          authorizer: verify-token

  dailyQuestionsCreate:
    handler: handlers/dailyQuestions.create
    events:
      - http:
          path: daily_questions
          method: post
          cors: true
          authorizer: verify-token

  dailyQuestionsGetOne:
    handler: handlers/dailyQuestions.getOne
    events:
      - http:
          path: daily_questions/{id}
          method: get
          cors: true
          authorizer: verify-token
  dailyQuestionsGetAll:
    handler: handlers/dailyQuestions.getAll
    events:
      - http:
          path: daily_questions
          method: get
          cors: true
          authorizer: verify-token

  dailyQuestionsUpdate:
    handler: handlers/dailyQuestions.update
    events:
      - http:
          path: daily_questions/{id}
          method: put
          cors: true
          authorizer: verify-token
  dailyQuestionsDelete:
    handler: handlers/dailyQuestions.delete
    events:
      - http:
          path: daily_questions/{id}
          method: delete
          cors: true
          authorizer: verify-token

plugins:
  - serverless-offline
  - serverless-mocha-plugin
