service: daily-questions-service

frameworkVersion: '>=1.1.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  stage: v1
  region: us-east-1

plugins:
  - serverless-offline

functions:
  verify-token:
    handler: api/handlers/auth/VerifyToken.auth

  login:
    handler: api/handlers/auth/AuthHandler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  register:
    handler: api/handlers/auth/AuthHandler.register
    events:
      - http:
          path: register
          method: post
          cors: true

  me:
    handler: api/handlers/auth/AuthHandler.me
    events:
      - http:
          path: user
          method: get
          cors: true
          authorizer: verify-token

  getQuestionsByUserId:
    handler: api/handlers/user/UserHandler.getQuestionsByUserId
    events:
      - http:
          path: user/questions
          method: get
          cors: true
          authorizer: verify-token

  getUsers:
    handler: api/handlers/user/UserHandler.getUsers
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: verify-token

  configFeatures:
    handler: api/handlers/config/ConfigHandler.features
    events:
      - http:
          path: config/features
          method: get
          cors: true
          authorizer: verify-token

  poc:
    handler: api/handlers/config/ConfigHandler.poc
    events:
      - http:
          path: poc
          method: get
          cors: true

  create:
    handler: api/handlers/dailyQuestions/DailyQuestionsHandler.create
    events:
      - http:
          path: daily_questions
          method: post
          cors: true
          authorizer: verify-token

  getOne:
    handler: api/handlers/dailyQuestions/DailyQuestionsHandler.getOne
    events:
      - http:
          path: daily_questions/{id}
          method: get
          cors: true
          authorizer: verify-token
  getAll:
    handler: api/handlers/dailyQuestions/DailyQuestionsHandler.getAll
    events:
      - http:
          path: daily_questions
          method: get
          cors: true
          authorizer: verify-token

  update:
    handler: api/handlers/dailyQuestions/DailyQuestionsHandler.update
    events:
      - http:
          path: daily_questions/{id}
          method: put
          cors: true
          authorizer: verify-token
  delete:
    handler: api/handlers/dailyQuestions/DailyQuestionsHandler.delete
    events:
      - http:
          path: daily_questions/{id}
          method: delete
          cors: true
          authorizer: verify-token
