service: daily-questions-service

frameworkVersion: '>=1.1.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  stage: v1
  region: us-east-1

plugins:
  - serverless-offline

functions:
  create:
    handler: api/functions/dailyQuestions.create
    events:
      - http:
          path: daily_questions
          method: post
          cors: true
  getOne:
    handler: api/functions/dailyQuestions.getOne
    events:
      - http:
          path: daily_questions/{id}
          method: get
          cors: true
  getAll:
    handler: api/functions/dailyQuestions.getAll
    events:
      - http:
          path: daily_questions
          method: get
          cors: true
  update:
    handler: api/functions/dailyQuestions.update
    events:
      - http:
          path: daily_questions/{id}
          method: put
          cors: true
  delete:
    handler: api/functions/dailyQuestions.delete
    events:
      - http:
          path: daily_questions/{id}
          method: delete
          cors: true
